### ISSUE TITLE
geting error

### ISSUE THREAD

**Issue by Manish347** [mobcode1337/DM-Killer#2]
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: requests in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: pxhttps in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 3)) (420420.6969)
Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 4)) (1.5.2)
ERROR: Could not find a version that satisfies the requirement ctypes (from versions: none)
ERROR: No matching distribution found for ctypes
Press any key to continue . . .

running python 3.10.0

**Comment by TheRookie5619** [comment]
Are you trying to run it on replit Replit doesn't support ctypes it should install easily on windows and linux.

**Comment by Manish347** [comment]
its on window and i am running via cmd have a look in img
![Screenshot 2022-12-28 230100](https://user-images.githubusercontent.com/61860765/209850380-043d51f8-b431-47e5-96ed-e483b64a55d6.png)
